Fix for Python 3, print function
In Python 3, the print statement has been replaced with a print() function.  When using python3 I was getting:

```
  File "./check_disk", line 27
    print str(err) # will print something like "option -a not recognized"
            ^
SyntaxError: invalid syntax
```

and

```
  File "./check_disk", line 102
    print message
                ^
SyntaxError: Missing parentheses in call to 'print'
```

With this change these errors are gone and it works with python3.  Thanks.